environment:
  order: baked_bell_pepper
  horizon: 17
reward:
  communication_penalty: 0.0
  forced_communication_penalty: 0.05
  paired_comm_reward_enabled: true
  paired_comm_request_positive_reward: 0.5
  paired_comm_request_negative_reward: -0.1
  paired_comm_response_positive_reward: 0.5
  paired_comm_response_negative_reward: -0.1
  paired_comm_deny_reward: 1.0
trainer:
  type: mappo
  collect_only: true
  off_policy_snapshots: runs/rl/snapshots/one_episode_t3_t16.jsonl
  rollout_dir: rollouts_kl
  output_dir: runs/rl/collect
  model_path: /datacache/LLMs/Qwen2.5-7B-Instruct
  lora_path: null
  actor_adapters:
    agent_0:
      adapter_name: Chef
      lora_path: ./runs/Chef
    agent_1:
      adapter_name: Assistant
      lora_path: ./runs/Assistant
  critic_adapter:
    adapter_name: critic
    lora_path: ./runs/adapter_critic/critic
    lora_config:
      r: 16
      alpha: 32
      dropout: 0.05
  value_head_path: ./runs/value_head.pt
  latest_model_path_file: runs/rl/latest_model.json
  generation_temperature: 0.7
  evaluation_batch_size: 6
  max_new_tokens: 512
  vllm_request_timeout: 180
  compute_values_in_collect: true
  collect_value_backend: vllm
  fix_mistral_regex: true
agents:
  num_agents: 2
  agent_0:
    type: vllm
    model: qwen2.5-7B-instruct
    api_key: YOUR_API_KEY
    base_url: http://127.0.0.1:9000/v1
    temperature: 0
    max_tokens: 512
    timeout: 180
    max_retries: 3
    role: Chef
    local_model_path: /datacache/LLMs/Qwen2.5-7B-Instruct
    cuda_visible_devices:
    - 0
    data_parallel_size: 1
  agent_1:
    type: vllm
    model: qwen2.5-7B-instruct
    api_key: YOUR_API_KEY
    base_url: http://127.0.0.1:9001/v1
    temperature: 0
    max_tokens: 512
    timeout: 180
    max_retries: 3
    role: Assistant
    local_model_path: /datacache/LLMs/Qwen2.5-7B-Instruct
    cuda_visible_devices:
    - 1
    data_parallel_size: 1
