environment:
  layout: "cramped_room"
  order: "baked_bell_pepper"
  horizon: 24

reward:
  communication_penalty: 0.1
  forced_communication_penalty: 0.4

trainer:
  type: "mappo"
  train_only: true
  collect_only: false
  fix_mistral_regex: true
  max_records_per_step: 10

  model_path: /datacache/LLMs/Qwen2.5-7B-Instruct
  lora_path: null
  lora: {}
  actor_adapters:
    agent_0:
      adapter_name: Chef
      lora_path: ./runs/Chef
    agent_1:
      adapter_name: Assistant
      lora_path: ./runs/Assistant
  critic_adapter:
    adapter_name: critic
    lora_path: null
    lora_config:
      r: 8
      alpha: 16
      dropout: 0.05

  rollout_dir: "./rollouts_kl"
  output_dir: "runs/rl/train_kl"
  initial_rollout_cache_dir: runs/rl/train_kl/initial_rollout_cache
  save_interval: 10
  checkpoint_interval: 0

  export_latest_dir: "runs/rl/export_latest_kl"
  latest_model_path_file: "runs/rl/latest_model_kl.json"
  apply_latest_model_override: true
  export_interval: 1

  max_new_tokens: 512
  generation_temperature: 0.0
  evaluation_batch_size: 1

  gamma: 0.99
  gae_lambda: 0.95
  actor_lr: 1.0e-6
  critic_lr: 3.0e-7
  value_head_lr: 1.0e-6
  lr_scheduler: linear
  lr_warmup_updates: 0
  lr_min_ratio: 0.0
  train_batch_size: 1
  update_epochs: 1
  gradient_checkpointing: true
  gradient_accumulation_steps: 4
  target_kl: 0.01
  kl_penalty_coef: 0.05
  clip_coef: 0.15
  entropy_coef: 0.01
  value_coef: 0.5
  max_grad_norm: 0.5
  cleanup_rollouts: true

agents:
  num_agents: 2
  agent_0:
    type: "openai"
    model: "qwen2.5-7b"
    api_key: "YOUR_API_KEY"
    base_url: "http://127.0.0.1:8000/v1"
    model_dirname: ""
    temperature: 0
    max_tokens: 512
    timeout: 30
    max_retries: 3
    role: "Chef"
  agent_1:
    type: "openai"
    model: "qwen2.5-7b"
    api_key: "YOUR_API_KEY"
    base_url: "http://127.0.0.1:8001/v1"
    model_dirname: ""
    temperature: 0
    max_tokens: 512
    timeout: 30
    max_retries: 3
    role: "Assistant"
